[variables]
NIXPACKS_PHP_COMPOSER_INSTALL_COMMAND = 'composer install --no-dev --optimize-autoloader --no-scripts'

[phases.install]
cmds = ['mkdir -p bootstrap/cache']

[phases.build] 
cmds = [
  'cp .env.build .env',
  'composer install --no-dev --optimize-autoloader --no-scripts',
  'npm ci --production=false',
  'npm run build',
  'php artisan package:discover --ansi',
  'rm .env',
  'chmod +x startup.sh'
]

[phases.start]
cmd = './startup.sh'